name = "DICOMTree"
uuid = "c4d2416d-3439-49b0-a3b3-18bf95df003e"
authors = ["François de Kermenguy"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
